apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: dynatracealertings.monitoring.crossplane.io
spec:
  group: monitoring.crossplane.io
  names:
    kind: DynatraceAlerting
    plural: dynatracealertings
  categories:
    - monitoring
    - alerting
    - observability
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    alertingConfig:
                      type: object
                      description: The alerting configuration details
                      properties:
                        schemaId:
                          type: string
                          description: The schema identifier for Dynatrace
                          default: builtin:alerting.profile
                        schemaVersion:
                          type: string
                          description: The schema version to use
                          default: "8.5"
                        scope:
                          type: string
                          description: The scope of the alerting configuration
                          default: environment
                        value:
                          type: object
                          description: The alerting configuration value
                          properties:
                            name:
                              type: string
                              description: The name of the alerting profile
                            severityRules:
                              type: array
                              description: List of severity rules for this alerting profile
                              items:
                                type: object
                                properties:
                                  delayInMinutes:
                                    type: integer
                                    description: Delay in minutes before triggering the alert
                                    default: 0
                                  severityLevel:
                                    type: string
                                    description: The severity level for this rule
                                    enum:
                                      - AVAILABILITY
                                      - CUSTOM_ALERT
                                      - ERROR
                                      - PERFORMANCE
                                      - RESOURCE_CONTENTION
                                      - RESOURCE_LIMITATION
                                      - SECURITY
                                      - USAGE
                                  tagFilter:
                                    type: array
                                    description: |-
                                      List of tags to filter on
                                      Optional field that can be used to filter alerts
                                    items:
                                      type: string
                                  tagFilterIncludeMode:
                                    type: string
                                    description: Tag filter include mode for this rule
                                    enum:
                                      - ALL_PROBLEMS
                                      - ONLY_OPEN_PROBLEMS
                                      - ONLY_CLOSED_PROBLEMS
                                required:
                                  - severityLevel
                                  - delayInMinutes
                                  - tagFilterIncludeMode
                              x-kubernetes-list-type: atomic
                          required:
                            - name
                      required:
                        - value
                    applicationRef:
                      type: object
                      description: Reference to the application this alerting configuration applies to
                      properties:
                        name:
                          type: string
                          description: The name of the application
                        namespace:
                          type: string
                          description: |-
                            The Kubernetes namespace where the application is deployed
                            Defaults to the default namespace
                          default: default
                      required:
                        - name
                  required:
                    - applicationRef
                    - alertingConfig
              required:
                - parameters
          required:
            - spec
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type==Ready)].status
          description: Ready Status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
          description: Age
