apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: kubernetesclusters.platform.example.org
spec:
  group: platform.example.org
  names:
    kind: KubernetesCluster
    plural: kubernetesclusters
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    enableAutoScaling:
                      type: boolean
                      default: false
                    highAvailability:
                      type: boolean
                      default: false
                    maxNodes:
                      type: integer
                      default: 10
                    minNodes:
                      type: integer
                      default: 1
                    nodeCount:
                      type: integer
                    nodeSize:
                      type: string
                    region:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                    version:
                      type: string
                      default: "1.28"
                  required:
                    - nodeCount
                    - nodeSize
                    - region
              required:
                - parameters
          required:
            - spec
