apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: multischemaalertrules.monitoring.example.org
spec:
  group: monitoring.example.org
  names:
    kind: MultiSchemaAlertRule
    plural: multischemaalertrules
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    delayInMinutes:
                      type: integer
                      default: 0
                    severityLevel:
                      type: object
                      enum:
                        - AVAILABILITY
                        - CUSTOM_ALERT
                        - ERROR
                        - PERFORMANCE
                        - RESOURCE_CONTENTION
                        - RESOURCE_LIMITATION
                        - SECURITY
                        - USAGE
                    tagFilter:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    tagFilterIncludeMode:
                      type: object
                      enum:
                        - ALL_PROBLEMS
                        - ONLY_OPEN_PROBLEMS
                        - ONLY_CLOSED_PROBLEMS
                  required:
                    - severityLevel
                    - delayInMinutes
                    - tagFilterIncludeMode
              required:
                - parameters
          required:
            - spec
