apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: postgresqlinstances.database.example.org
spec:
  group: database.example.org
  names:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    backupRetentionDays:
                      type: integer
                      default: 7
                    instanceSize:
                      type: string
                    storageGB:
                      type: integer
                    version:
                      type: string
                      default: "15"
                  required:
                    - storageGB
              required:
                - parameters
          required:
            - spec
