apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databases.example.org
spec:
  group: example.org
  names:
    kind: Database
    plural: databases
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Regular fields go to spec.parameters
                      pattern: ^[a-z0-9-]+$
                    region:
                      type: string
                      default: us-east-1
                    replicas:
                      type: integer
                      default: 3
                      minimum: 1
                      maximum: 10
                  required:
                    - name
                publishConnectionDetailsTo:
                  type: object
                  properties:
                    configRef:
                      type: string
                    metadata:
                      type: object
                      additionalProperties: true
                    name:
                      type: string
                      description: Publish connection details configuration
                  required:
                    - name
                writeConnectionSecretToRef:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Connection secret reference for storing credentials
                    namespace:
                      type: string
                  required:
                    - name
              required:
                - parameters
            status:
              type: object
              properties:
                endpoint:
                  type: string
                phase:
                  type: string
                ready:
                  type: boolean
                  description: Status for the database
              required:
                - ready
          required:
            - spec
