apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: validatedresources.example.org
spec:
  group: example.org
  names:
    kind: ValidatedResource
    plural: validatedresources
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    age:
                      type: integer
                      minimum: 0
                      maximum: 120
                    description:
                      type: string
                      minLength: 10
                      maxLength: 500
                    email:
                      type: string
                      pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
                    name:
                      type: string
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                      minLength: 3
                      maxLength: 63
                    resourceId:
                      type: string
                      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
                      x-kubernetes-immutable: true
                    status:
                      type: string
                      default: pending
                      enum:
                        - pending
                        - active
                        - inactive
                        - deleted
                  required:
                    - name
                    - resourceId
              required:
                - parameters
          required:
            - spec
